name: Cashew-API Docker Image CI

on:
  push:
    branches: [ "dev" ]
    
jobs:
  build-cashew:
    name: Build and Push Cashew API Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{secrets.DOCKER_USER}}/cashew:latest
  
  build-localstack-bootstrap:
    name: Build and Push Localstack-bootstrap Image
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build And Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./docker/localstack-bootstrap
          tags: ${{secrets.DOCKER_USER}}/localstack-bootstrap:latest
